version: '3.8'


services:
  db:
    image: postgres:latest
    volumes:
      - ./database:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
    restart: always
    environment:
      - POSTGRES_USER=ndushakov
      - POSTGRES_PASSWORD=1234567890
      - POSTGRES_DB=okkam

  web:
    build: ./api
    command: python -m core
    ports:
      - 80:80
    restart: always
    environment:
      - DATABASE_URL=postgresql+asyncpg://ndushakov:1234567890@db:5432/okkam
    depends_on:
      - db
